- src/QueryResult.php
> fix uint64 type cast

- src/Issue.php
> Прокидываем полную ошибку запроса, убираем дублирование логики

- CHANGELOG.md
- README.md
- src/Iam.php
Fix #30
Add static token auth.
> Add IAM access authentication

- CHANGELOG.md
- src/Traits/RequestTrait.php
- tests/RetryOnBadSessionTest.php
> Fixed retry at BAD_SESSION

- CHANGELOG.md
- src/Jwt/Jwt.php
> Fix JWT token

- CHANGELOG.md
- src/Auth/IamAuth.php
- src/Ydb.php
> Fix IamAuth.php

- .github/workflows/tests.yml
- CHANGELOG.md
- composer.json
- src/Ydb.php
> Add support of php 7.2

- CHANGELOG.md
- src/QueryResult.php
- tests/CheckTypeTest.php
> Fixed crash when getting an empty list in QueryResult

- CHANGELOG.md
- README.md
- src/Auth/EnvironCredentials.php
- tests/TestEnvTypes.php
- tests/some.json
> Added environment credentials

- CHANGELOG.md
- src/Logger/SampleStdLogger.php
- src/Logger/SimpleStdLogger.php
- src/Ydb.php
> Add simple logger

- CHANGELOG.md
- src/Session.php
> Fix key name in createTable function

- CHANGELOG.md
- src/Sessions/MemorySessionPool.php
> Update destructor in MemorySessionPool.php

- CHANGELOG.md
- src/Traits/RequestTrait.php
- src/Ydb.php
> Fix discovery on exception

- CHANGELOG.md
- src/QueryResult.php
- src/Types/TimestampType.php
- src/Version.php
- tests/CheckTypeTest.php
> Added microseconds in Timestamp type

- CHANGELOG.md
- src/Auth/Auth.php
- src/Auth/Implement/AccessTokenAuthentication.php
- src/Auth/Implement/AnonymousAuthentication.php
- src/Auth/Implement/JwtWithJsonAuthentication.php
- src/Auth/Implement/JwtWithPrivateKeyAuthentication.php
- src/Auth/Implement/MetadataAuthentication.php
- src/Auth/Implement/OAuthTokenAuthentication.php
- src/Auth/TokenInfo.php
- src/Iam.php
- tests/CheckRefreshTokenRatioTest.php
- tests/RefreshTokenTest.php
> Create refresh token ratio parameter

- CHANGELOG.md
- src/Auth/IamAuth.php
- src/Iam.php
- src/Retry/Retry.php
- src/Traits/RequestTrait.php
> Update logs in retry and iam

- CHANGELOG.md
- src/Table.php
- tests/CheckParamsInRetryTransactionTest.php
- tests/RetryOnExceptionTest.php
> Add lambda on exception in retryTransaction

- src/Table.php
> Fix retryTransactions params

- .github/workflows/sumplelinter.yml
- composer.json
> Add simple linter

- CHANGELOG.md
- slo-workload/Dockerfile
- src/Session.php
- tests/CheckTimeoutAndDurationParamsTest.php
> Added query timeout and cancled

- CHANGELOG.md
- README.md
- src/YdbQuery.php
- tests/CheckTxSettingsTest.php
> Add snapshot mode in noninteractive transaction

- CHANGELOG.md
- README.md
- src/Ydb.php
- tests/LoggerCheckTest.php
> Added logger as YDB config

- CHANGELOG.md
- src/QueryResult.php
- src/Traits/TypeValueHelpersTrait.php
- src/Types/YsonType.php
- tests/CheckTypeTest.php
> Add Yson type

- CHANGELOG.md
- src/Session.php
- src/YdbQuery.php
- tests/KeepInCacheTest.php
> Remove keep in cache by default false in YdbQuery

- .github/workflows/tests.yml
- tests/QueryStatsTest.php
> Create matrix tests

- protos/Ydb/Table/ExecuteScanQueryRequest.php
> default query mode for scan requests

- CHANGELOG.md
- src/QueryResult.php
> Исправлена ошибка с отсутствующим rows

- CHANGELOG.md
- protos/Ydb/Table/ExecuteScanQueryRequest.php
- src/Enums/ScanQueryMode.php
- src/Table.php
- tests/ScanQueryTest.php
> Added `ScanQueryMode` for `Table::scanQuery`

- .github/workflows/slo.yml
- .github/workflows/tests.yml
- tests/StaticCredentialsTest.php
> workaround for denied with underscore in password

- CHANGELOG.md
- src/Traits/RequestTrait.php
> fix: Error parsing JSON @1:9: No such field
